// Shared in-memory store for all tasks endpoints
export let tasksStore = [
  {
    id: 'TASK-001',
    title: 'Fix homepage layout issues',
    description: 'The hero section has alignment problems on mobile devices.',
    status: 'in-progress',
    assignee: 'D',
    priority: 'high',
    progress: 65,
    tags: ['frontend', 'urgent'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'TASK-002',
    title: 'Implement user authentication',
    description: 'Set up JWT-based authentication system.',
    status: 'in-progress',
    assignee: 'R',
    priority: 'high',
    progress: 45,
    tags: ['backend', 'security'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'TASK-003',
    title: 'Design dashboard UI',
    description: 'Create mockups for the new admin dashboard.',
    status: 'done',
    assignee: 'D',
    priority: 'medium',
    progress: 100,
    tags: ['design'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'TASK-004',
    title: 'Setup database migrations',
    description: 'Create initial database schema and migrations.',
    status: 'done',
    assignee: 'R',
    priority: 'high',
    progress: 100,
    tags: ['backend', 'database'],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'TASK-005',
    title: 'Write API documentation',
    description: 'Document all REST endpoints with examples.',
    status: 'backlog',
    assignee: 'H',
    priority: 'medium',
    progress: 0,
    tags: ['documentation'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'TASK-006',
    title: 'Optimize database queries',
    description: 'Profile and improve slow queries.',
    status: 'in-review',
    assignee: 'R',
    priority: 'medium',
    progress: 80,
    tags: ['performance', 'backend'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export let activitiesStore = [
  {
    type: 'task_moved',
    message: 'TASK-006 moved to In Review by RawrBot',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    agent: 'RawrBot',
  },
  {
    type: 'task_completed',
    message: 'TASK-004 marked as complete',
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    agent: 'RawrBot',
  },
  {
    type: 'progress',
    message: 'TASK-001 progress updated to 65%',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    agent: 'Derek',
  },
];
